# Generated by Django 5.1.3 on 2024-12-21 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
